config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :customers
  resources :orders do
    member do
      get :new_item
    end
  end
  root 'site#index'
  resources :products

end

app/models/customer.rb
class Customer
  include Mongoid::Document
  include Mongoid::Timestamps::Short

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""


  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  has_many :orders

  def self.select_options
    Customer.all.map { |c| [c.email, c.id.to_s] }
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
    @q = params[:q]
    @customers = @customers.any_of({name: /#{@q}/i}, {email: /#{@q}/i}) if @q
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_customer
    @customer = Customer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def customer_params
    params.require(:customer).permit(:name, :email)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.slim
= form_for @customer, html: {class: 'ui form'} do |f|
  - if @customer.errors.any?
    #error_explanation
      h2 = "#{pluralize(@customer.errors.count, "error")} prohibited this customer from being saved:"
      ul
        - @customer.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :email
    = f.text_field :email

  .actions = f.submit class: 'ui button primary'

app/views/customers/edit.html.slim
h1 Editing customer

== render 'form'

= link_to 'Show', @customer
'|
= link_to 'Back', customers_path

app/views/customers/index.html.slim
h1 Listing customers

= render 'commons/search_tag', search_path: customers_path, placeholder: 'Search customers'

table.ui.table
  thead
    tr
      th Email
      th
      th
      th

  tbody
    - @customers.each do |customer|
      tr
        td = customer.email
        td = link_to 'Show', customer
        td = link_to 'Edit', edit_customer_path(customer)
        td = link_to 'Destroy', customer, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Customer', new_customer_path, class: 'ui button primary'

app/views/customers/new.html.slim
h1 New customer

== render 'form'

= link_to 'Back', customers_path

app/views/customers/show.html.slim
p#notice = notice

p
  strong Email:
  = @customer.email

= link_to 'Edit', edit_customer_path(@customer)
'|
= link_to 'Back', customers_path