config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :customers
  resources :orders do
    member do
      get :new_item
    end
  end
  root 'site#index'
  resources :products

end

app/models/order.rb
class Order
  include Mongoid::Document
  include Mongoid::Timestamps::Short

  validates :customer, presence: true
  # validates :order_items, presence: true

  belongs_to :customer
  has_many :order_items

  accepts_nested_attributes_for :order_items

  def remove_flagged_items(params)
    if params[:order_items_attributes].blank?
      order_items.destroy_all
    else
      item_ids = params[:order_items_attributes].map { |id, _| id }
      order_items.each do |item|
        item.destroy unless item_ids.include? item.id.to_s
      end
    end
  end

  def total
    order_items.inject (0) { |sum, i| sum + i.total }
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
    @q = params[:q]
    if @q
      @orders = Customer.where({email: /#{@q}/i}).flat_map { |c| c.orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    @order.remove_flagged_items(order_params)
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def new_item
    item = OrderItem.new({order_id: params[:id], product_id: params[:product_id]})
    render partial: 'item', locals: {item: item}
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    # params.require(:order).permit(:customer_id, order_items_attributes: [:id, :product_id, :unit_price, :quantity, :total])
    params.require(:order).permit!
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_crumbs.html.slim
.ui.breadcrumb
  a.section = link_to 'Home', :root
  i.right.chevron.icon.divider
  a.section = link_to 'Orders', :orders
  i.right.chevron.icon.divider
  .active.section
    - unless @order.new_record?
      = @order.customer.email
      | 's Order
    - else
      | New Order

app/views/orders/_form.html.slim
= form_for @order, html: {class: 'order'} do |f|
  - if @order.errors.any?
    #error_explanation
      h2 = "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      ul
        - @order.errors.full_messages.each do |message|
          li = message

  .ui.form
    .field
      = f.label :customer_
      = f.select :customer_id, Customer.select_options

    h3 Items
    table.ui.table
      thead
        tr
          th Product
          th Unit Price
          th Quantity
          th Total
          th
      tbody.items
        - @order.order_items.each do |item|
          = render 'item', item: item

  .ui.search.column
    .ui.icon.input
      = text_field_tag nil, nil, class: 'search-products', placeholder: 'Search product', 'data-url' => new_item_order_path(@order.id)
      i.search.icon.circular

  .actions
    = f.submit class: 'ui primary button'
    = link_to 'Back', order_path(@order.id), class: 'ui button' unless @order.new_record

app/views/orders/_item.html.slim
tr.item
  = fields_for "order[order_items_attributes][#{item.id}]", item do |f|
    = f.hidden_field :id unless item.new_record?
    = f.hidden_field :product_id
    = f.hidden_field :unit_price, class: 'price'

    td = item.product.name
    td = item.unit_price
    td = f.number_field :quantity
    td.total = item.total
    td
      a.remove(data-target='.item') Remove

app/views/orders/edit.html.slim
= render 'crumbs'

h1 Editing order

== render 'form'

app/views/orders/index.html.slim
h1 Listing orders

= render 'commons/search_tag', search_path: orders_path, placeholder: 'Search by customer'

table.ui.table
  thead
    tr
      th Customer
      th Total
      th
      th
      th

  tbody
    - @orders.each do |order|
      tr
        td = order.customer.email
        td = order.total
        td = link_to 'Show', order
        td = link_to 'Edit', edit_order_path(order)
        td = link_to 'Destroy', order, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Order', new_order_path, class: 'ui button primary'

app/views/orders/new.html.slim
= render 'crumbs'

h1 New order

== render 'form'

app/views/orders/show.html.slim
= render 'crumbs'

p#notice = notice

p
  strong Customer:
  = @order.customer.email

b Items
table.ui.table
  thead
    tr
      th Product
      th Unit Price
      th Quantity
      th Total
  tbody
    - @order.order_items.each do |item|
      tr
        td = item.product.name
        td = item.unit_price
        td = item.quantity
        td = item.total

p
  strong Total:
  = @order.total



= link_to 'Edit', edit_order_path(@order), class: 'ui button primary'
= link_to 'Back', orders_path, class: 'ui button'