config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :customers
  resources :orders do
    member do
      get :new_item
    end
  end
  root 'site#index'
  resources :products

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="ui segment">
  <div class="ui page grid">
    <div class="column">
      <div class="ui menu">
        <div class="header item">
          <a href="/">Star Wars Coffee </a>
        </div>
        <% if customer_signed_in? %>
            <div class="right large menu">
              <%= link_to 'Products', :products, class: 'ui link item' %>
              <%= link_to 'Orders', :orders, class: 'ui link item' %>
              <%= link_to 'Customers', :customers, class: 'ui link item' %>
              <%= link_to  destroy_customer_session_path, method: :delete, class: 'ui link item' do %>
                  <i class="sign out icon"></i> Logout
              <% end %>
            </div>
        <% else %>
            <div class="right large menu">
              <%= link_to 'Login', new_customer_session_path, class: 'ui link item' %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="ui segment">
  <div class="ui page grid">
    <div class="column">
      <%= yield %>
    </div>
  </div>
</div>

<div class="ui footer vertical gray segment">
  <div class="ui page grid">
    <div class="column"> Copyright 2015 Chromedia Far East, Inc.
    </div>
  </div>
</div>

</body>
</html>